# -*- coding: utf-8 -*-
################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING
################################################################################
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDockWidget,
    QFrame, QGraphicsView, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QListView,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QProgressBar, QPushButton, QScrollArea,
    QSizePolicy, QSlider, QSpacerItem, QSpinBox,
    QTabWidget, QVBoxLayout, QWidget)
from app.ui.widgets.sortable_widgets import TargetVideosListWidget
from app.ui.core import media_rc
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1548, 768)
        font = QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/media/media/visomaster_small.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionLoad_Embeddings = QAction(MainWindow)
        self.actionLoad_Embeddings.setObjectName(u"actionLoad_Embeddings")
        self.actionSave_Embeddings = QAction(MainWindow)
        self.actionSave_Embeddings.setObjectName(u"actionSave_Embeddings")
        self.actionSave_Embeddings_As = QAction(MainWindow)
        self.actionSave_Embeddings_As.setObjectName(u"actionSave_Embeddings_As")
        self.actionOpen_Videos_Folder = QAction(MainWindow)
        self.actionOpen_Videos_Folder.setObjectName(u"actionOpen_Videos_Folder")
        self.actionOpen_Video_Files = QAction(MainWindow)
        self.actionOpen_Video_Files.setObjectName(u"actionOpen_Video_Files")
        self.actionLoad_Source_Images_Folder = QAction(MainWindow)
        self.actionLoad_Source_Images_Folder.setObjectName(u"actionLoad_Source_Images_Folder")
        self.actionLoad_Source_Image_Files = QAction(MainWindow)
        self.actionLoad_Source_Image_Files.setObjectName(u"actionLoad_Source_Image_Files")
        self.actionView_Fullscreen_F11 = QAction(MainWindow)
        self.actionView_Fullscreen_F11.setObjectName(u"actionView_Fullscreen_F11")
        self.actionView_Help_Shortcuts = QAction(MainWindow)
        self.actionView_Help_Shortcuts.setObjectName(u"actionView_Help_Shortcuts")
        self.actionView_Help_Presets = QAction(MainWindow)
        self.actionView_Help_Presets.setObjectName(u"actionView_Help_Presets")
        self.actionTest = QAction(MainWindow)
        self.actionTest.setObjectName(u"actionTest")
        self.actionLoad_Saved_Workspace = QAction(MainWindow)
        self.actionLoad_Saved_Workspace.setObjectName(u"actionLoad_Saved_Workspace")
        self.actionSave_Current_Workspace = QAction(MainWindow)
        self.actionSave_Current_Workspace.setObjectName(u"actionSave_Current_Workspace")
        self.actionTest_2 = QAction(MainWindow)
        self.actionTest_2.setObjectName(u"actionTest_2")
        self.actionLoad_SavedWorkspace = QAction(MainWindow)
        self.actionLoad_SavedWorkspace.setObjectName(u"actionLoad_SavedWorkspace")
        self.actionReset_to_LastWorkspace = QAction(MainWindow)
        self.actionReset_to_LastWorkspace.setObjectName(u"actionReset_to_LastWorkspace")
        self.actionSave_LastWorkspace = QAction(MainWindow)
        self.actionSave_LastWorkspace.setObjectName(u"actionSave_LastWorkspace")
        self.actionQuit_WithoutSaving = QAction(MainWindow)
        self.actionQuit_WithoutSaving.setObjectName(u"actionQuit_WithoutSaving")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionSave_CurrentWorkspace = QAction(MainWindow)
        self.actionSave_CurrentWorkspace.setObjectName(u"actionSave_CurrentWorkspace")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.mediaLayout = QWidget(self.centralwidget)
        self.mediaLayout.setObjectName(u"mediaLayout")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mediaLayout.sizePolicy().hasHeightForWidth())
        self.mediaLayout.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.mediaLayout)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.panelVisibilityCheckBoxLayout = QHBoxLayout()
        self.panelVisibilityCheckBoxLayout.setObjectName(u"panelVisibilityCheckBoxLayout")
        self.TargetMediaCheckBox = QCheckBox(self.mediaLayout)
        self.TargetMediaCheckBox.setObjectName(u"TargetMediaCheckBox")
        self.TargetMediaCheckBox.setChecked(True)
        self.panelVisibilityCheckBoxLayout.addWidget(self.TargetMediaCheckBox)
        self.InputFacesCheckBox = QCheckBox(self.mediaLayout)
        self.InputFacesCheckBox.setObjectName(u"InputFacesCheckBox")
        self.InputFacesCheckBox.setChecked(True)
        self.panelVisibilityCheckBoxLayout.addWidget(self.InputFacesCheckBox)
        self.JobsCheckBox = QCheckBox(self.mediaLayout)
        self.JobsCheckBox.setObjectName(u"JobsCheckBox")
        self.JobsCheckBox.setChecked(True)
        self.panelVisibilityCheckBoxLayout.addWidget(self.JobsCheckBox)
        self.facesPanelCheckBox = QCheckBox(self.mediaLayout)
        self.facesPanelCheckBox.setObjectName(u"facesPanelCheckBox")
        self.facesPanelCheckBox.setChecked(True)
        self.panelVisibilityCheckBoxLayout.addWidget(self.facesPanelCheckBox)
        self.parametersPanelCheckBox = QCheckBox(self.mediaLayout)
        self.parametersPanelCheckBox.setObjectName(u"parametersPanelCheckBox")
        self.parametersPanelCheckBox.setChecked(True)
        self.panelVisibilityCheckBoxLayout.addWidget(self.parametersPanelCheckBox)
        self.horizontalSpacer_8 = QSpacerItem(20, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.panelVisibilityCheckBoxLayout.addItem(self.horizontalSpacer_8)
        self.faceCompareCheckBox = QCheckBox(self.mediaLayout)
        self.faceCompareCheckBox.setObjectName(u"faceCompareCheckBox")
        self.panelVisibilityCheckBoxLayout.addWidget(self.faceCompareCheckBox)
        self.faceMaskCheckBox = QCheckBox(self.mediaLayout)
        self.faceMaskCheckBox.setObjectName(u"faceMaskCheckBox")
        self.panelVisibilityCheckBoxLayout.addWidget(self.faceMaskCheckBox)
        self.verticalLayout.addLayout(self.panelVisibilityCheckBoxLayout)
        self.graphicsViewFrame = QGraphicsView(self.mediaLayout)
        self.graphicsViewFrame.setObjectName(u"graphicsViewFrame")
        self.verticalLayout.addWidget(self.graphicsViewFrame)
        self.verticalLayoutMediaControls = QVBoxLayout()
        self.verticalLayoutMediaControls.setObjectName(u"verticalLayoutMediaControls")
        self.horizontalLayoutMediaSlider = QHBoxLayout()
        self.horizontalLayoutMediaSlider.setObjectName(u"horizontalLayoutMediaSlider")
        self.timelineScrollArea = QScrollArea(self.mediaLayout)
        self.timelineScrollArea.setObjectName(u"timelineScrollArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.timelineScrollArea.sizePolicy().hasHeightForWidth())
        self.timelineScrollArea.setSizePolicy(sizePolicy1)
        self.timelineScrollArea.setMinimumSize(QSize(0, 40))
        self.timelineScrollArea.setMaximumSize(QSize(16777215, 40))
        self.timelineScrollArea.setWidgetResizable(True)
        self.timelineScrollArea.setFrameShape(QFrame.Shape.NoFrame)
        self.timelineScrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.verticalLayout_timeline = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_timeline.setObjectName(u"verticalLayout_timeline")
        self.verticalLayout_timeline.setContentsMargins(0, 0, 0, 0)
        self.videoSeekSlider = QSlider(self.scrollAreaWidgetContents)
        self.videoSeekSlider.setObjectName(u"videoSeekSlider")
        self.videoSeekSlider.setOrientation(Qt.Orientation.Horizontal)
        self.verticalLayout_timeline.addWidget(self.videoSeekSlider)
        self.timelineScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutMediaSlider.addWidget(self.timelineScrollArea)
        self.videoSeekLineEdit = QLineEdit(self.mediaLayout)
        self.videoSeekLineEdit.setObjectName(u"videoSeekLineEdit")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.videoSeekLineEdit.sizePolicy().hasHeightForWidth())
        self.videoSeekLineEdit.setSizePolicy(sizePolicy2)
        self.videoSeekLineEdit.setMaximumSize(QSize(70, 16777215))
        self.videoSeekLineEdit.setClearButtonEnabled(False)
        self.horizontalLayoutMediaSlider.addWidget(self.videoSeekLineEdit)
        self.zoomLabel = QLabel(self.mediaLayout)
        self.zoomLabel.setObjectName(u"zoomLabel")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.zoomLabel.sizePolicy().hasHeightForWidth())
        self.zoomLabel.setSizePolicy(sizePolicy3)
        self.horizontalLayoutMediaSlider.addWidget(self.zoomLabel)
        self.timelineZoomSlider = QSlider(self.mediaLayout)
        self.timelineZoomSlider.setObjectName(u"timelineZoomSlider")
        sizePolicy2.setHeightForWidth(self.timelineZoomSlider.sizePolicy().hasHeightForWidth())
        self.timelineZoomSlider.setSizePolicy(sizePolicy2)
        self.timelineZoomSlider.setMinimumSize(QSize(100, 0))
        self.timelineZoomSlider.setMaximumSize(QSize(100, 16777215))
        self.timelineZoomSlider.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalLayoutMediaSlider.addWidget(self.timelineZoomSlider)
        self.verticalLayoutMediaControls.addLayout(self.horizontalLayoutMediaSlider)
        self.horizontalLayoutMediaButtons = QHBoxLayout()
        self.horizontalLayoutMediaButtons.setObjectName(u"horizontalLayoutMediaButtons")
        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer_7)
        self.liveSoundButton = QPushButton(self.mediaLayout)
        self.liveSoundButton.setObjectName(u"liveSoundButton")
        self.liveSoundButton.setMinimumSize(QSize(0, 0))
        icon1 = QIcon()
        icon1.addFile(u":/media/media/audio_off.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.liveSoundButton.setIcon(icon1)
        self.liveSoundButton.setIconSize(QSize(16, 20))
        self.liveSoundButton.setCheckable(True)
        self.liveSoundButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.liveSoundButton)
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer)
        self.frameRewindButton = QPushButton(self.mediaLayout)
        self.frameRewindButton.setObjectName(u"frameRewindButton")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frameRewindButton.sizePolicy().hasHeightForWidth())
        self.frameRewindButton.setSizePolicy(sizePolicy4)
        self.frameRewindButton.setMaximumSize(QSize(100, 16777215))
        icon2 = QIcon()
        icon2.addFile(u":/media/media/tl_left_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.frameRewindButton.setIcon(icon2)
        self.frameRewindButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.frameRewindButton)
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer_3)
        self.buttonMediaRecord = QPushButton(self.mediaLayout)
        self.buttonMediaRecord.setObjectName(u"buttonMediaRecord")
        icon3 = QIcon()
        icon3.addFile(u":/media/media/rec_off.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttonMediaRecord.setIcon(icon3)
        self.buttonMediaRecord.setCheckable(True)
        self.buttonMediaRecord.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.buttonMediaRecord)
        self.horizontalSpacer_6 = QSpacerItem(30, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer_6)
        self.buttonMediaPlay = QPushButton(self.mediaLayout)
        self.buttonMediaPlay.setObjectName(u"buttonMediaPlay")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.buttonMediaPlay.sizePolicy().hasHeightForWidth())
        self.buttonMediaPlay.setSizePolicy(sizePolicy5)
        self.buttonMediaPlay.setMaximumSize(QSize(100, 16777215))
        icon4 = QIcon()
        icon4.addFile(u":/media/media/play_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttonMediaPlay.setIcon(icon4)
        self.buttonMediaPlay.setCheckable(True)
        self.buttonMediaPlay.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.buttonMediaPlay)
        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer_4)
        self.frameAdvanceButton = QPushButton(self.mediaLayout)
        self.frameAdvanceButton.setObjectName(u"frameAdvanceButton")
        sizePolicy4.setHeightForWidth(self.frameAdvanceButton.sizePolicy().hasHeightForWidth())
        self.frameAdvanceButton.setSizePolicy(sizePolicy4)
        self.frameAdvanceButton.setMaximumSize(QSize(100, 16777215))
        icon5 = QIcon()
        icon5.addFile(u":/media/media/tl_right_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.frameAdvanceButton.setIcon(icon5)
        self.frameAdvanceButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.frameAdvanceButton)
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer_2)
        self.addMarkerButton = QPushButton(self.mediaLayout)
        self.addMarkerButton.setObjectName(u"addMarkerButton")
        icon6 = QIcon()
        icon6.addFile(u":/media/media/add_marker_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.addMarkerButton.setIcon(icon6)
        self.addMarkerButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.addMarkerButton)
        self.removeMarkerButton = QPushButton(self.mediaLayout)
        self.removeMarkerButton.setObjectName(u"removeMarkerButton")
        icon7 = QIcon()
        icon7.addFile(u":/media/media/remove_marker_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.removeMarkerButton.setIcon(icon7)
        self.removeMarkerButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.removeMarkerButton)
        self.previousMarkerButton = QPushButton(self.mediaLayout)
        self.previousMarkerButton.setObjectName(u"previousMarkerButton")
        icon8 = QIcon()
        icon8.addFile(u":/media/media/previous_marker_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.previousMarkerButton.setIcon(icon8)
        self.previousMarkerButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.previousMarkerButton)
        self.nextMarkerButton = QPushButton(self.mediaLayout)
        self.nextMarkerButton.setObjectName(u"nextMarkerButton")
        icon9 = QIcon()
        icon9.addFile(u":/media/media/next_marker_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.nextMarkerButton.setIcon(icon9)
        self.nextMarkerButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.nextMarkerButton)
        self.viewFullScreenButton = QPushButton(self.mediaLayout)
        self.viewFullScreenButton.setObjectName(u"viewFullScreenButton")
        icon10 = QIcon()
        icon10.addFile(u":/media/media/fullscreen.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.viewFullScreenButton.setIcon(icon10)
        self.viewFullScreenButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.viewFullScreenButton)
        self.theatreModeButton = QPushButton(self.mediaLayout)
        self.theatreModeButton.setObjectName(u"theatreModeButton")
        icon11 = QIcon()
        icon11.addFile(u":/media/media/theatre_hover.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.theatreModeButton.setIcon(icon11)
        self.theatreModeButton.setFlat(True)
        self.horizontalLayoutMediaButtons.addWidget(self.theatreModeButton)
        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayoutMediaButtons.addItem(self.horizontalSpacer_5)
        self.verticalLayoutMediaControls.addLayout(self.horizontalLayoutMediaButtons)
        self.verticalLayout.addLayout(self.verticalLayoutMediaControls)
        self.verticalSpacer = QSpacerItem(20, 5, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        self.verticalLayout.addItem(self.verticalSpacer)
        self.facesPanelGroupBox = QGroupBox(self.mediaLayout)
        self.facesPanelGroupBox.setObjectName(u"facesPanelGroupBox")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.facesPanelGroupBox.sizePolicy().hasHeightForWidth())
        self.facesPanelGroupBox.setSizePolicy(sizePolicy6)
        self.facesPanelGroupBox.setMinimumSize(QSize(0, 220))
        self.facesPanelGroupBox.setMaximumSize(QSize(16777215, 16777215))
        self.facesPanelGroupBox.setAutoFillBackground(False)
        self.facesPanelGroupBox.setFlat(True)
        self.facesPanelGroupBox.setCheckable(False)
        self.gridLayout_2 = QGridLayout(self.facesPanelGroupBox)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.facesButtonsWidget = QWidget(self.facesPanelGroupBox)
        self.facesButtonsWidget.setObjectName(u"facesButtonsWidget")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.facesButtonsWidget.sizePolicy().hasHeightForWidth())
        self.facesButtonsWidget.setSizePolicy(sizePolicy7)
        self.verticalLayout_8 = QVBoxLayout(self.facesButtonsWidget)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalWidget = QWidget(self.facesButtonsWidget)
        self.verticalWidget.setObjectName(u"verticalWidget")
        self.controlButtonsLayout = QVBoxLayout(self.verticalWidget)
        self.controlButtonsLayout.setSpacing(8)
        self.controlButtonsLayout.setObjectName(u"controlButtonsLayout")
        self.controlButtonsLayout.setContentsMargins(0, 4, 0, 4)
        self.findTargetFacesButton = QPushButton(self.verticalWidget)
        self.findTargetFacesButton.setObjectName(u"findTargetFacesButton")
        self.findTargetFacesButton.setMinimumSize(QSize(100, 0))
        self.findTargetFacesButton.setCheckable(False)
        self.findTargetFacesButton.setFlat(True)
        self.controlButtonsLayout.addWidget(self.findTargetFacesButton)
        self.clearTargetFacesButton = QPushButton(self.verticalWidget)
        self.clearTargetFacesButton.setObjectName(u"clearTargetFacesButton")
        self.clearTargetFacesButton.setCheckable(False)
        self.clearTargetFacesButton.setFlat(True)
        self.controlButtonsLayout.addWidget(self.clearTargetFacesButton)
        self.swapfacesButton = QPushButton(self.verticalWidget)
        self.swapfacesButton.setObjectName(u"swapfacesButton")
        self.swapfacesButton.setCheckable(True)
        self.swapfacesButton.setFlat(True)
        self.controlButtonsLayout.addWidget(self.swapfacesButton)
        self.editFacesButton = QPushButton(self.verticalWidget)
        self.editFacesButton.setObjectName(u"editFacesButton")
        self.editFacesButton.setCheckable(True)
        self.editFacesButton.setFlat(True)
        self.controlButtonsLayout.addWidget(self.editFacesButton)
        self.verticalLayout_8.addWidget(self.verticalWidget)
        self.gridLayout_2.addWidget(self.facesButtonsWidget, 1, 0, 1, 1)
        self.inputEmbeddingsList = QListWidget(self.facesPanelGroupBox)
        self.inputEmbeddingsList.setObjectName(u"inputEmbeddingsList")
        sizePolicy8 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy8.setHorizontalStretch(4)
        sizePolicy8.setVerticalStretch(0)
        sizePolicy8.setHeightForWidth(self.inputEmbeddingsList.sizePolicy().hasHeightForWidth())
        self.inputEmbeddingsList.setSizePolicy(sizePolicy8)
        self.inputEmbeddingsList.setMinimumSize(QSize(320, 120))
        self.inputEmbeddingsList.setMaximumSize(QSize(16777215, 120))
        self.inputEmbeddingsList.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputEmbeddingsList.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.inputEmbeddingsList.setAutoScroll(False)
        self.inputEmbeddingsList.setMovement(QListView.Movement.Static)
        self.inputEmbeddingsList.setLayoutMode(QListView.LayoutMode.Batched)
        self.inputEmbeddingsList.setSpacing(4)
        self.inputEmbeddingsList.setViewMode(QListView.ViewMode.IconMode)
        self.inputEmbeddingsList.setUniformItemSizes(True)
        self.inputEmbeddingsList.setProperty(u"wrapping", True)
        self.gridLayout_2.addWidget(self.inputEmbeddingsList, 1, 2, 1, 1)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.saveImageButton = QPushButton(self.facesPanelGroupBox)
        self.saveImageButton.setObjectName(u"saveImageButton")
        self.saveImageButton.setFlat(True)
        self.horizontalLayout_4.addWidget(self.saveImageButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.batchLayout_1 = QHBoxLayout()
        self.batchLayout_1.setObjectName(u"batchLayout_1")
        self.batchImageButton = QPushButton(self.facesPanelGroupBox)
        self.batchImageButton.setObjectName(u"batchImageButton")
        self.batchImageButton.setFlat(True)
        self.batchLayout_1.addWidget(self.batchImageButton)
        self.batchallImageButton = QPushButton(self.facesPanelGroupBox)
        self.batchallImageButton.setObjectName(u"batchallImageButton")
        self.batchallImageButton.setFlat(True)
        self.batchLayout_1.addWidget(self.batchallImageButton)
        self.gridLayout_2.addLayout(self.batchLayout_1, 0, 1, 1, 1)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.inputEmbeddingsSearchBox = QLineEdit(self.facesPanelGroupBox)
        self.inputEmbeddingsSearchBox.setObjectName(u"inputEmbeddingsSearchBox")
        self.horizontalLayout_3.addWidget(self.inputEmbeddingsSearchBox)
        self.openEditorButton = QPushButton(self.facesPanelGroupBox)
        self.openEditorButton.setObjectName(u"openEditorButton")
        self.openEditorButton.setCheckable(False)
        self.openEditorButton.setFlat(True)
        self.horizontalLayout_3.addWidget(self.openEditorButton)
        self.openEmbeddingButton = QPushButton(self.facesPanelGroupBox)
        self.openEmbeddingButton.setObjectName(u"openEmbeddingButton")
        icon12 = QIcon()
        icon12.addFile(u":/media/media/open_file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.openEmbeddingButton.setIcon(icon12)
        self.openEmbeddingButton.setFlat(True)
        self.horizontalLayout_3.addWidget(self.openEmbeddingButton)
        self.saveEmbeddingButton = QPushButton(self.facesPanelGroupBox)
        self.saveEmbeddingButton.setObjectName(u"saveEmbeddingButton")
        icon13 = QIcon()
        icon13.addFile(u":/media/media/save_file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.saveEmbeddingButton.setIcon(icon13)
        self.saveEmbeddingButton.setFlat(True)
        self.horizontalLayout_3.addWidget(self.saveEmbeddingButton)
        self.saveEmbeddingAsButton = QPushButton(self.facesPanelGroupBox)
        self.saveEmbeddingAsButton.setObjectName(u"saveEmbeddingAsButton")
        icon14 = QIcon()
        icon14.addFile(u":/media/media/save_file_as.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.saveEmbeddingAsButton.setIcon(icon14)
        self.saveEmbeddingAsButton.setFlat(True)
        self.horizontalLayout_3.addWidget(self.saveEmbeddingAsButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.targetFacesList = QListWidget(self.facesPanelGroupBox)
        self.targetFacesList.setObjectName(u"targetFacesList")
        self.targetFacesList.setAutoFillBackground(True)
        self.targetFacesList.setAutoScroll(False)
        self.gridLayout_2.addWidget(self.targetFacesList, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.facesPanelGroupBox)
        self.horizontalLayout.addWidget(self.mediaLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.input_Target_DockWidget = QDockWidget(MainWindow)
        self.input_Target_DockWidget.setObjectName(u"input_Target_DockWidget")
        sizePolicy9 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy9.setHorizontalStretch(4)
        sizePolicy9.setVerticalStretch(0)
        sizePolicy9.setHeightForWidth(self.input_Target_DockWidget.sizePolicy().hasHeightForWidth())
        self.input_Target_DockWidget.setSizePolicy(sizePolicy9)
        self.input_Target_DockWidget.setMinimumSize(QSize(324, 230))
        self.input_Target_DockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout_4 = QGridLayout(self.dockWidgetContents)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.vboxLayout = QVBoxLayout()
        self.vboxLayout.setObjectName(u"vboxLayout")
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.targetVideosPathLineEdit = QLineEdit(self.dockWidgetContents)
        self.targetVideosPathLineEdit.setObjectName(u"targetVideosPathLineEdit")
        self.targetVideosPathLineEdit.setReadOnly(True)
        self.horizontalLayout_7.addWidget(self.targetVideosPathLineEdit)
        self.buttonTargetVideosPath = QPushButton(self.dockWidgetContents)
        self.buttonTargetVideosPath.setObjectName(u"buttonTargetVideosPath")
        sizePolicy2.setHeightForWidth(self.buttonTargetVideosPath.sizePolicy().hasHeightForWidth())
        self.buttonTargetVideosPath.setSizePolicy(sizePolicy2)
        self.buttonTargetVideosPath.setMinimumSize(QSize(0, 0))
        icon15 = QIcon()
        icon15.addFile(u":/glyphs/media/glyphs/folder_on.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttonTargetVideosPath.setIcon(icon15)
        self.buttonTargetVideosPath.setIconSize(QSize(18, 18))
        self.buttonTargetVideosPath.setFlat(True)
        self.horizontalLayout_7.addWidget(self.buttonTargetVideosPath)
        self.vboxLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_7b = QHBoxLayout()
        self.horizontalLayout_7b.setObjectName(u"horizontalLayout_7b")
        self.targetVideosSearchBox = QLineEdit(self.dockWidgetContents)
        self.targetVideosSearchBox.setObjectName(u"targetVideosSearchBox")
        self.horizontalLayout_7b.addWidget(self.targetVideosSearchBox)
        self.targetVideosSearchResetButton = QPushButton(self.dockWidgetContents)
        self.targetVideosSearchResetButton.setObjectName(u"targetVideosSearchResetButton")
        self.targetVideosSearchResetButton.setMinimumSize(QSize(38, 0))
        icon16 = QIcon()
        icon16.addFile(u":/glyphs/media/glyphs/times_on.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon16.addFile(u":/glyphs/media/glyphs/times_on.svg", QSize(), QIcon.Mode.Active, QIcon.State.Off)
        icon16.addFile(u":/glyphs/media/glyphs/times_on.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.targetVideosSearchResetButton.setIcon(icon16)
        self.horizontalLayout_7b.addWidget(self.targetVideosSearchResetButton)
        self.vboxLayout.addLayout(self.horizontalLayout_7b)
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.targetVideosSortComboBox = QComboBox(self.dockWidgetContents)
        self.targetVideosSortComboBox.addItem("")
        self.targetVideosSortComboBox.setObjectName(u"targetVideosSortComboBox")
        sizePolicy10 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy10.setHorizontalStretch(0)
        sizePolicy10.setVerticalStretch(0)
        sizePolicy10.setHeightForWidth(self.targetVideosSortComboBox.sizePolicy().hasHeightForWidth())
        self.targetVideosSortComboBox.setSizePolicy(sizePolicy10)
        self.horizontalLayout_9.addWidget(self.targetVideosSortComboBox)
        self.sortTargetVideosDirectionButton = QPushButton(self.dockWidgetContents)
        self.sortTargetVideosDirectionButton.setObjectName(u"sortTargetVideosDirectionButton")
        self.sortTargetVideosDirectionButton.setMinimumSize(QSize(38, 0))
        icon17 = QIcon()
        icon17.addFile(u":/glyphs/media/glyphs/sort-amount-down_bold.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon17.addFile(u":/glyphs/media/glyphs/sort-amount-up_bold.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.sortTargetVideosDirectionButton.setIcon(icon17)
        self.sortTargetVideosDirectionButton.setIconSize(QSize(18, 18))
        self.sortTargetVideosDirectionButton.setCheckable(True)
        self.horizontalLayout_9.addWidget(self.sortTargetVideosDirectionButton)
        self.targetVideosFilterMenuButton = QPushButton(self.dockWidgetContents)
        self.targetVideosFilterMenuButton.setObjectName(u"targetVideosFilterMenuButton")
        self.targetVideosFilterMenuButton.setMinimumSize(QSize(38, 0))
        icon18 = QIcon()
        icon18.addFile(u":/glyphs/media/glyphs/filter_bold.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon18.addFile(u":/glyphs/media/glyphs/filter_on.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.targetVideosFilterMenuButton.setIcon(icon18)
        self.targetVideosFilterMenuButton.setIconSize(QSize(18, 18))
        self.targetVideosFilterMenuButton.setFlat(False)
        self.horizontalLayout_9.addWidget(self.targetVideosFilterMenuButton)
        self.vboxLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_9a = QHBoxLayout()
        self.horizontalLayout_9a.setObjectName(u"horizontalLayout_9a")
        self.label_4 = QLabel(self.dockWidgetContents)
        self.label_4.setObjectName(u"label_4")
        self.horizontalLayout_9a.addWidget(self.label_4)
        self.targetVideosFilterImagesCheckBox = QCheckBox(self.dockWidgetContents)
        self.targetVideosFilterImagesCheckBox.setObjectName(u"targetVideosFilterImagesCheckBox")
        icon19 = QIcon()
        icon19.addFile(u":/glyphs/media/glyphs/images_bold.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon19.addFile(u":/glyphs/media/glyphs/images_on.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.targetVideosFilterImagesCheckBox.setIcon(icon19)
        self.targetVideosFilterImagesCheckBox.setIconSize(QSize(18, 18))
        self.targetVideosFilterImagesCheckBox.setChecked(True)
        self.horizontalLayout_9a.addWidget(self.targetVideosFilterImagesCheckBox)
        self.targetVideosFilterVideosCheckBox = QCheckBox(self.dockWidgetContents)
        self.targetVideosFilterVideosCheckBox.setObjectName(u"targetVideosFilterVideosCheckBox")
        self.targetVideosFilterVideosCheckBox.setEnabled(True)
        icon20 = QIcon()
        icon20.addFile(u":/glyphs/media/glyphs/film_duo.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon20.addFile(u":/glyphs/media/glyphs/film_on.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.targetVideosFilterVideosCheckBox.setIcon(icon20)
        self.targetVideosFilterVideosCheckBox.setIconSize(QSize(18, 18))
        self.targetVideosFilterVideosCheckBox.setChecked(True)
        self.horizontalLayout_9a.addWidget(self.targetVideosFilterVideosCheckBox)
        self.targetVideosFilterWebcamsCheckBox = QCheckBox(self.dockWidgetContents)
        self.targetVideosFilterWebcamsCheckBox.setObjectName(u"targetVideosFilterWebcamsCheckBox")
        icon21 = QIcon()
        icon21.addFile(u":/glyphs/media/glyphs/camcorder_bold.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon21.addFile(u":/glyphs/media/glyphs/camcorder_on.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.targetVideosFilterWebcamsCheckBox.setIcon(icon21)
        self.targetVideosFilterWebcamsCheckBox.setIconSize(QSize(18, 18))
        self.targetVideosFilterWebcamsCheckBox.setCheckable(True)
        # FORK: marcado por padrao. Desmarcado, a webcam simplesmente NAO
        # APARECE na lista de alvos — e nada na interface indica que existe um
        # filtro escondendo ela. Para um fluxo de avatar ao vivo, a webcam e o
        # alvo principal, entao esconde-la por padrao e o contrario do esperado.
        self.targetVideosFilterWebcamsCheckBox.setChecked(True)
        self.horizontalLayout_9a.addWidget(self.targetVideosFilterWebcamsCheckBox)
        self.vboxLayout.addLayout(self.horizontalLayout_9a)
        self.horizontalLayout_9b_gridLayout_3 = QGridLayout()
        self.horizontalLayout_9b_gridLayout_3.setObjectName(u"horizontalLayout_9b_gridLayout_3")
        self.horizontalLayout_9b_gridLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.targetVideosWidthSlider = QSlider(self.dockWidgetContents)
        self.targetVideosWidthSlider.setObjectName(u"targetVideosWidthSlider")
        self.targetVideosWidthSlider.setMinimum(0)
        self.targetVideosWidthSlider.setMaximum(7680)
        self.targetVideosWidthSlider.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalLayout_9b_gridLayout_3.addWidget(self.targetVideosWidthSlider, 0, 1, 1, 1)
        self.label_3 = QLabel(self.dockWidgetContents)
        self.label_3.setObjectName(u"label_3")
        self.horizontalLayout_9b_gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.targetVideosHeightSpinBox = QSpinBox(self.dockWidgetContents)
        self.targetVideosHeightSpinBox.setObjectName(u"targetVideosHeightSpinBox")
        self.targetVideosHeightSpinBox.setMaximumSize(QSize(82, 16777215))
        self.horizontalLayout_9b_gridLayout_3.addWidget(self.targetVideosHeightSpinBox, 1, 2, 1, 1)
        self.targetVideosHeightSlider = QSlider(self.dockWidgetContents)
        self.targetVideosHeightSlider.setObjectName(u"targetVideosHeightSlider")
        self.targetVideosHeightSlider.setMinimum(0)
        self.targetVideosHeightSlider.setMaximum(4320)
        self.targetVideosHeightSlider.setOrientation(Qt.Orientation.Horizontal)
        self.horizontalLayout_9b_gridLayout_3.addWidget(self.targetVideosHeightSlider, 1, 1, 1, 1)
        self.label_2 = QLabel(self.dockWidgetContents)
        self.label_2.setObjectName(u"label_2")
        self.horizontalLayout_9b_gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.targetVideosWidthSpinBox = QSpinBox(self.dockWidgetContents)
        self.targetVideosWidthSpinBox.setObjectName(u"targetVideosWidthSpinBox")
        self.targetVideosWidthSpinBox.setMaximumSize(QSize(82, 16777215))
        self.horizontalLayout_9b_gridLayout_3.addWidget(self.targetVideosWidthSpinBox, 0, 2, 1, 1)
        self.vboxLayout.addLayout(self.horizontalLayout_9b_gridLayout_3)
        self.targetVideosListProgressBar = QProgressBar(self.dockWidgetContents)
        self.targetVideosListProgressBar.setObjectName(u"targetVideosListProgressBar")
        self.targetVideosListProgressBar.setMaximum(0)
        self.targetVideosListProgressBar.setValue(0)
        self.targetVideosListProgressBar.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.targetVideosListProgressBar.setTextVisible(True)
        self.vboxLayout.addWidget(self.targetVideosListProgressBar)
        self.targetVideosList = TargetVideosListWidget(self.dockWidgetContents)
        self.targetVideosList.setObjectName(u"targetVideosList")
        self.targetVideosList.setAcceptDrops(True)
        self.targetVideosList.setAutoScroll(False)
        self.vboxLayout.addWidget(self.targetVideosList)
        self.gridLayout_4.addLayout(self.vboxLayout, 0, 0, 1, 1)
        self.input_Target_DockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.input_Target_DockWidget)
        self.input_Faces_DockWidget = QDockWidget(MainWindow)
        self.input_Faces_DockWidget.setObjectName(u"input_Faces_DockWidget")
        sizePolicy9.setHeightForWidth(self.input_Faces_DockWidget.sizePolicy().hasHeightForWidth())
        self.input_Faces_DockWidget.setSizePolicy(sizePolicy9)
        self.input_Faces_DockWidget.setMinimumSize(QSize(340, 230))
        self.input_Faces_DockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents_Faces = QWidget()
        self.dockWidgetContents_Faces.setObjectName(u"dockWidgetContents_Faces")
        self.gridLayout_Faces = QGridLayout(self.dockWidgetContents_Faces)
        self.gridLayout_Faces.setObjectName(u"gridLayout_Faces")
        self.vboxLayout_Faces = QVBoxLayout()
        self.vboxLayout_Faces.setObjectName(u"vboxLayout_Faces")
        self.horizontalLayout_Faces = QHBoxLayout()
        self.horizontalLayout_Faces.setObjectName(u"horizontalLayout_Faces")
        self.inputFacesPathLineEdit = QLineEdit(self.dockWidgetContents_Faces)
        self.inputFacesPathLineEdit.setObjectName(u"inputFacesPathLineEdit")
        self.inputFacesPathLineEdit.setReadOnly(True)
        self.horizontalLayout_Faces.addWidget(self.inputFacesPathLineEdit)
        self.buttonInputFacesPath = QPushButton(self.dockWidgetContents_Faces)
        self.buttonInputFacesPath.setObjectName(u"buttonInputFacesPath")
        sizePolicy2.setHeightForWidth(self.buttonInputFacesPath.sizePolicy().hasHeightForWidth())
        self.buttonInputFacesPath.setSizePolicy(sizePolicy2)
        self.buttonInputFacesPath.setIconSize(QSize(18, 18))
        self.buttonInputFacesPath.setFlat(True)
        self.horizontalLayout_Faces.addWidget(self.buttonInputFacesPath)
        self.vboxLayout_Faces.addLayout(self.horizontalLayout_Faces)
        self.inputFacesSearchBox = QLineEdit(self.dockWidgetContents_Faces)
        self.inputFacesSearchBox.setObjectName(u"inputFacesSearchBox")
        self.vboxLayout_Faces.addWidget(self.inputFacesSearchBox)
        self.inputFacesList = QListWidget(self.dockWidgetContents_Faces)
        self.inputFacesList.setObjectName(u"inputFacesList")
        self.inputFacesList.setAcceptDrops(True)
        self.inputFacesList.setAutoScroll(False)
        self.vboxLayout_Faces.addWidget(self.inputFacesList)
        self.gridLayout_Faces.addLayout(self.vboxLayout_Faces, 0, 0, 1, 1)
        self.input_Faces_DockWidget.setWidget(self.dockWidgetContents_Faces)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.input_Faces_DockWidget)
        self.jobManagerDockWidget = QDockWidget(MainWindow)
        self.jobManagerDockWidget.setObjectName(u"jobManagerDockWidget")
        self.jobManagerDockWidget.setMinimumSize(QSize(324, 230))
        self.jobManagerDockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents_JobManager = QWidget()
        self.dockWidgetContents_JobManager.setObjectName(u"dockWidgetContents_JobManager")
        self.verticalLayout_JobManager = QVBoxLayout(self.dockWidgetContents_JobManager)
        self.verticalLayout_JobManager.setObjectName(u"verticalLayout_JobManager")
        self.jobControlLayout = QHBoxLayout()
        self.jobControlLayout.setObjectName(u"jobControlLayout")
        self.addJobButton = QPushButton(self.dockWidgetContents_JobManager)
        self.addJobButton.setObjectName(u"addJobButton")
        self.jobControlLayout.addWidget(self.addJobButton)
        self.loadJobButton = QPushButton(self.dockWidgetContents_JobManager)
        self.loadJobButton.setObjectName(u"loadJobButton")
        self.jobControlLayout.addWidget(self.loadJobButton)
        self.deleteJobButton = QPushButton(self.dockWidgetContents_JobManager)
        self.deleteJobButton.setObjectName(u"deleteJobButton")
        self.jobControlLayout.addWidget(self.deleteJobButton)
        self.verticalLayout_JobManager.addLayout(self.jobControlLayout)
        self.refreshJobListButton = QPushButton(self.dockWidgetContents_JobManager)
        self.refreshJobListButton.setObjectName(u"refreshJobListButton")
        self.verticalLayout_JobManager.addWidget(self.refreshJobListButton)
        self.jobQueueList = QListWidget(self.dockWidgetContents_JobManager)
        self.jobQueueList.setObjectName(u"jobQueueList")
        self.jobQueueList.setSortingEnabled(True)
        self.verticalLayout_JobManager.addWidget(self.jobQueueList)
        self.processControlLayout = QHBoxLayout()
        self.processControlLayout.setObjectName(u"processControlLayout")
        self.buttonProcessAll = QPushButton(self.dockWidgetContents_JobManager)
        self.buttonProcessAll.setObjectName(u"buttonProcessAll")
        self.processControlLayout.addWidget(self.buttonProcessAll)
        self.buttonProcessSelected = QPushButton(self.dockWidgetContents_JobManager)
        self.buttonProcessSelected.setObjectName(u"buttonProcessSelected")
        self.processControlLayout.addWidget(self.buttonProcessSelected)
        self.verticalLayout_JobManager.addLayout(self.processControlLayout)
        self.jobManagerDockWidget.setWidget(self.dockWidgetContents_JobManager)
        MainWindow.addDockWidget(Qt.DockWidgetArea.LeftDockWidgetArea, self.jobManagerDockWidget)
        self.controlOptionsDockWidget = QDockWidget(MainWindow)
        self.controlOptionsDockWidget.setObjectName(u"controlOptionsDockWidget")
        self.controlOptionsDockWidget.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.gridLayout_5 = QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.tabWidget = QTabWidget(self.dockWidgetContents_2)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy11 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy11.setHorizontalStretch(1)
        sizePolicy11.setVerticalStretch(0)
        sizePolicy11.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy11)
        font1 = QFont()
        font1.setFamilies([u"Segoe UI Semibold"])
        font1.setPointSize(10)
        font1.setBold(True)
        self.tabWidget.setFont(font1)
        self.tabWidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.face_swap_tab = QWidget()
        self.face_swap_tab.setObjectName(u"face_swap_tab")
        self.verticalLayout_4 = QVBoxLayout(self.face_swap_tab)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.swapWidgetsLayout = QVBoxLayout()
        self.swapWidgetsLayout.setObjectName(u"swapWidgetsLayout")
        self.verticalLayout_4.addLayout(self.swapWidgetsLayout)
        self.tabWidget.addTab(self.face_swap_tab, "")
        self.face_editor_tab = QWidget()
        self.face_editor_tab.setObjectName(u"face_editor_tab")
        self.verticalLayout_3 = QVBoxLayout(self.face_editor_tab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.faceEditorWidgetsLayout = QVBoxLayout()
        self.faceEditorWidgetsLayout.setObjectName(u"faceEditorWidgetsLayout")
        self.verticalLayout_3.addLayout(self.faceEditorWidgetsLayout)
        self.tabWidget.addTab(self.face_editor_tab, "")
        self.common_tab = QWidget()
        self.common_tab.setObjectName(u"common_tab")
        self.commonWidgetsLayout_1 = QVBoxLayout(self.common_tab)
        self.commonWidgetsLayout_1.setObjectName(u"commonWidgetsLayout_1")
        self.commonWidgetsLayout = QVBoxLayout()
        self.commonWidgetsLayout.setObjectName(u"commonWidgetsLayout")
        self.commonWidgetsLayout_1.addLayout(self.commonWidgetsLayout)
        self.tabWidget.addTab(self.common_tab, "")
        self.denoiser_tab = QWidget()
        self.denoiser_tab.setObjectName(u"denoiser_tab")
        self.denoiserWidgetsLayout_1 = QVBoxLayout(self.denoiser_tab)
        self.denoiserWidgetsLayout_1.setObjectName(u"denoiserWidgetsLayout_1")
        self.denoiserWidgetsLayout = QVBoxLayout()
        self.denoiserWidgetsLayout.setObjectName(u"denoiserWidgetsLayout")
        self.denoiserWidgetsLayout_1.addLayout(self.denoiserWidgetsLayout)
        self.tabWidget.addTab(self.denoiser_tab, "")
        self.settings_tab = QWidget()
        self.settings_tab.setObjectName(u"settings_tab")
        self.verticalLayout_2 = QVBoxLayout(self.settings_tab)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label = QLabel(self.settings_tab)
        self.label.setObjectName(u"label")
        self.verticalLayout_2.addWidget(self.label)
        self.settingsWidgetsLayout = QVBoxLayout()
        self.settingsWidgetsLayout.setObjectName(u"settingsWidgetsLayout")
        self.outputFolderSelectionLayout = QHBoxLayout()
        self.outputFolderSelectionLayout.setObjectName(u"outputFolderSelectionLayout")
        self.outputFolderLineEdit = QLineEdit(self.settings_tab)
        self.outputFolderLineEdit.setObjectName(u"outputFolderLineEdit")
        self.outputFolderLineEdit.setReadOnly(True)
        self.outputFolderSelectionLayout.addWidget(self.outputFolderLineEdit)
        self.outputFolderButton = QPushButton(self.settings_tab)
        self.outputFolderButton.setObjectName(u"outputFolderButton")
        self.outputFolderButton.setFlat(False)
        self.outputFolderSelectionLayout.addWidget(self.outputFolderButton)
        self.outputOpenButton = QPushButton(self.settings_tab)
        self.outputOpenButton.setObjectName(u"outputOpenButton")
        self.outputOpenButton.setFlat(False)
        self.outputFolderSelectionLayout.addWidget(self.outputOpenButton)
        self.settingsWidgetsLayout.addLayout(self.outputFolderSelectionLayout)
        self.verticalLayout_2.addLayout(self.settingsWidgetsLayout)
        self.tabWidget.addTab(self.settings_tab, "")
        self.preset_tab = QWidget()
        self.preset_tab.setObjectName(u"preset_tab")
        self.presetsWidgetsLayout_1 = QVBoxLayout(self.preset_tab)
        self.presetsWidgetsLayout_1.setObjectName(u"presetsWidgetsLayout_1")
        self.labelp = QLabel(self.preset_tab)
        self.labelp.setObjectName(u"labelp")
        self.presetsWidgetsLayout_1.addWidget(self.labelp)
        self.presetsWidgetsLayout = QVBoxLayout()
        self.presetsWidgetsLayout.setObjectName(u"presetsWidgetsLayout")
        self.presetsList = QListWidget(self.preset_tab)
        self.presetsList.setObjectName(u"presetsList")
        self.presetsList.setSortingEnabled(True)
        self.presetsList.setMinimumSize(QSize(0, 360))
        self.presetsList.setMaximumSize(QSize(16777215, 460))
        self.presetsWidgetsLayout.addWidget(self.presetsList)
        self.presetsButtonsLayout = QHBoxLayout()
        self.presetsButtonsLayout.setObjectName(u"presetsButtonsLayout")
        self.applyPresetButton = QPushButton(self.preset_tab)
        self.applyPresetButton.setObjectName(u"applyPresetButton")
        self.presetsButtonsLayout.addWidget(self.applyPresetButton)
        self.savePresetButton = QPushButton(self.preset_tab)
        self.savePresetButton.setObjectName(u"savePresetButton")
        self.presetsButtonsLayout.addWidget(self.savePresetButton)
        self.controlPresetButton = QPushButton(self.preset_tab)
        self.controlPresetButton.setObjectName(u"controlPresetButton")
        self.controlPresetButton.setCheckable(True)
        self.presetsButtonsLayout.addWidget(self.controlPresetButton)
        self.presetsWidgetsLayout.addLayout(self.presetsButtonsLayout)
        self.presetsWidgetsLayout_1.addLayout(self.presetsWidgetsLayout)
        self.verticalSpacerpresets = QSpacerItem(0, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.presetsWidgetsLayout_1.addItem(self.verticalSpacerpresets)
        self.tabWidget.addTab(self.preset_tab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.vramProgressBar = QProgressBar(self.dockWidgetContents_2)
        self.vramProgressBar.setObjectName(u"vramProgressBar")
        self.vramProgressBar.setValue(24)
        self.horizontalLayout_2.addWidget(self.vramProgressBar)
        self.clearMemoryButton = QPushButton(self.dockWidgetContents_2)
        self.clearMemoryButton.setObjectName(u"clearMemoryButton")
        self.clearMemoryButton.setFlat(True)
        self.horizontalLayout_2.addWidget(self.clearMemoryButton)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.controlOptionsDockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.controlOptionsDockWidget)
        self.topMenuBar = QMenuBar(MainWindow)
        self.topMenuBar.setObjectName(u"topMenuBar")
        self.topMenuBar.setGeometry(QRect(0, 0, 1376, 33))
        self.menuFile = QMenu(self.topMenuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.topMenuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.topMenuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuHelp = QMenu(self.topMenuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.topMenuBar)
        self.topMenuBar.addAction(self.menuFile.menuAction())
        self.topMenuBar.addAction(self.menuEdit.menuAction())
        self.topMenuBar.addAction(self.menuView.menuAction())
        self.topMenuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionLoad_SavedWorkspace)
        self.menuFile.addAction(self.actionSave_CurrentWorkspace)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Videos_Folder)
        self.menuFile.addAction(self.actionOpen_Video_Files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Source_Images_Folder)
        self.menuFile.addAction(self.actionLoad_Source_Image_Files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Embeddings)
        self.menuFile.addAction(self.actionSave_Embeddings)
        self.menuFile.addAction(self.actionSave_Embeddings_As)
        self.menuEdit.addAction(self.actionTest_2)
        self.menuView.addAction(self.actionView_Fullscreen_F11)
        self.menuHelp.addAction(self.actionView_Help_Shortcuts)
        self.menuHelp.addAction(self.actionView_Help_Presets)
        self.retranslateUi(MainWindow)
        self.editFacesButton.setDefault(False)
        self.tabWidget.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi
    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"VisoMaster - Fusion - 1.0.0", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionLoad_Embeddings.setText(QCoreApplication.translate("MainWindow", u"Load Embeddings", None))
        self.actionSave_Embeddings.setText(QCoreApplication.translate("MainWindow", u"Save Embeddings", None))
        self.actionSave_Embeddings_As.setText(QCoreApplication.translate("MainWindow", u"Save Embeddings As", None))
        self.actionOpen_Videos_Folder.setText(QCoreApplication.translate("MainWindow", u"Load Target Images/Videos Folder", None))
        self.actionOpen_Video_Files.setText(QCoreApplication.translate("MainWindow", u"Load Target Image/Video Files", None))
        self.actionLoad_Source_Images_Folder.setText(QCoreApplication.translate("MainWindow", u"Load Source Images Folder", None))
        self.actionLoad_Source_Image_Files.setText(QCoreApplication.translate("MainWindow", u"Load Source Image Files", None))
        self.actionView_Fullscreen_F11.setText(QCoreApplication.translate("MainWindow", u"Fullscreen", None))
        self.actionView_Help_Shortcuts.setText(QCoreApplication.translate("MainWindow", u"View Shortcuts", None))
        self.actionView_Help_Presets.setText(QCoreApplication.translate("MainWindow", u"Presets", None))
        self.actionTest.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.actionLoad_Saved_Workspace.setText(QCoreApplication.translate("MainWindow", u"Load Saved Workspace", None))
        self.actionSave_Current_Workspace.setText(QCoreApplication.translate("MainWindow", u"Save Current Workspace", None))
        self.actionTest_2.setText(QCoreApplication.translate("MainWindow", u"Test", None))
        self.actionLoad_SavedWorkspace.setText(QCoreApplication.translate("MainWindow", u"Load Saved Workspace", None))
        self.actionReset_to_LastWorkspace.setText(QCoreApplication.translate("MainWindow", u"Reset to Last Workspace", None))
        self.actionSave_LastWorkspace.setText(QCoreApplication.translate("MainWindow", u"Save as Last Workspace", None))
        self.actionQuit_WithoutSaving.setText(QCoreApplication.translate("MainWindow", u"Quit without saving..", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionSave_CurrentWorkspace.setText(QCoreApplication.translate("MainWindow", u"Save Current Workspace", None))
        self.TargetMediaCheckBox.setText(QCoreApplication.translate("MainWindow", u"Target Videos/Images", None))
        self.InputFacesCheckBox.setText(QCoreApplication.translate("MainWindow", u"Input Faces", None))
        self.JobsCheckBox.setText(QCoreApplication.translate("MainWindow", u"Jobs", None))
        self.facesPanelCheckBox.setText(QCoreApplication.translate("MainWindow", u"Faces", None))
        self.parametersPanelCheckBox.setText(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.faceCompareCheckBox.setText(QCoreApplication.translate("MainWindow", u"Face Compare", None))
        self.faceMaskCheckBox.setText(QCoreApplication.translate("MainWindow", u"Face Mask", None))
#if QT_CONFIG(tooltip)
        self.videoSeekLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"Frame Number", None))
#endif // QT_CONFIG(tooltip)
        self.zoomLabel.setText(QCoreApplication.translate("MainWindow", u"Zoom - 100%", None))
#if QT_CONFIG(tooltip)
        self.timelineZoomSlider.setToolTip(QCoreApplication.translate("MainWindow", u"Zoom Timeline", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.liveSoundButton.setToolTip(QCoreApplication.translate("MainWindow", u"[Experimental] Toggle Live Sound while the video is playing", None))
#endif // QT_CONFIG(tooltip)
        self.liveSoundButton.setText("")
        self.frameRewindButton.setText("")
        self.buttonMediaRecord.setText("")
        self.buttonMediaPlay.setText("")
        self.frameAdvanceButton.setText("")
#if QT_CONFIG(tooltip)
        self.addMarkerButton.setToolTip(QCoreApplication.translate("MainWindow", u"Add Marker", None))
#endif // QT_CONFIG(tooltip)
        self.addMarkerButton.setText("")
#if QT_CONFIG(tooltip)
        self.removeMarkerButton.setToolTip(QCoreApplication.translate("MainWindow", u"Remove Marker", None))
#endif // QT_CONFIG(tooltip)
        self.removeMarkerButton.setText("")
#if QT_CONFIG(tooltip)
        self.previousMarkerButton.setToolTip(QCoreApplication.translate("MainWindow", u"Move to Previous Marker", None))
#endif // QT_CONFIG(tooltip)
        self.previousMarkerButton.setText("")
#if QT_CONFIG(tooltip)
        self.nextMarkerButton.setToolTip(QCoreApplication.translate("MainWindow", u"Move to Next Marker", None))
#endif // QT_CONFIG(tooltip)
        self.nextMarkerButton.setText("")
#if QT_CONFIG(tooltip)
        self.viewFullScreenButton.setToolTip(QCoreApplication.translate("MainWindow", u"View Fullscreen (F11)", None))
#endif // QT_CONFIG(tooltip)
        self.viewFullScreenButton.setText("")
#if QT_CONFIG(tooltip)
        self.theatreModeButton.setToolTip(QCoreApplication.translate("MainWindow", u"FullScreen Theatre (T)", None))
#endif // QT_CONFIG(tooltip)
        self.theatreModeButton.setText("")
        self.findTargetFacesButton.setText(QCoreApplication.translate("MainWindow", u"Find Faces", None))
        self.clearTargetFacesButton.setText(QCoreApplication.translate("MainWindow", u"Clear Faces", None))
        self.swapfacesButton.setText(QCoreApplication.translate("MainWindow", u"Swap Faces", None))
        self.editFacesButton.setText(QCoreApplication.translate("MainWindow", u"Edit Faces", None))
#if QT_CONFIG(tooltip)
        self.inputEmbeddingsList.setToolTip(QCoreApplication.translate("MainWindow", u"Saved Embedding", None))
#endif // QT_CONFIG(tooltip)
        self.saveImageButton.setText(QCoreApplication.translate("MainWindow", u"Save Image", None))
#if QT_CONFIG(tooltip)
        self.batchImageButton.setToolTip(QCoreApplication.translate("MainWindow", u"Processes the currently selected face across the entire target video or image.", None))
#endif // QT_CONFIG(tooltip)
        self.batchImageButton.setText(QCoreApplication.translate("MainWindow", u"Batch Process Selected Face\n"
"(For Videos and Images)", None))
#if QT_CONFIG(tooltip)
        self.batchallImageButton.setToolTip(QCoreApplication.translate("MainWindow", u"Processes all found faces. This feature is only available for target images, not videos.", None))
#endif // QT_CONFIG(tooltip)
        self.batchallImageButton.setText(QCoreApplication.translate("MainWindow", u"Batch Process All Faces\n"
"(For Images only)", None))
        self.inputEmbeddingsSearchBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search Embeddings", None))
#if QT_CONFIG(tooltip)
        self.openEditorButton.setToolTip(QCoreApplication.translate("MainWindow", u"Open Embedding Editor", None))
#endif // QT_CONFIG(tooltip)
        self.openEditorButton.setText(QCoreApplication.translate("MainWindow", u"Embedding Editor", None))
#if QT_CONFIG(tooltip)
        self.openEmbeddingButton.setToolTip(QCoreApplication.translate("MainWindow", u"Open Embedding File", None))
#endif // QT_CONFIG(tooltip)
        self.openEmbeddingButton.setText("")
#if QT_CONFIG(tooltip)
        self.saveEmbeddingButton.setToolTip(QCoreApplication.translate("MainWindow", u"Save all embeddings to the current file", None))
#endif // QT_CONFIG(tooltip)
        self.saveEmbeddingButton.setText("")
#if QT_CONFIG(tooltip)
        self.saveEmbeddingAsButton.setToolTip(QCoreApplication.translate("MainWindow", u"Save Embedding As", None))
#endif // QT_CONFIG(tooltip)
        self.saveEmbeddingAsButton.setText("")
        self.input_Target_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Target Videos", None))
        self.targetVideosPathLineEdit.setText("")
        self.targetVideosPathLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Select Videos/Images Path", None))
#if QT_CONFIG(tooltip)
        self.buttonTargetVideosPath.setToolTip(QCoreApplication.translate("MainWindow", u"Choose Target Media Folder", None))
#endif // QT_CONFIG(tooltip)
        self.buttonTargetVideosPath.setText("")
        self.targetVideosSearchBox.setText("")
        self.targetVideosSearchBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search Videos/Images", None))
        self.targetVideosSearchResetButton.setText("")
        self.targetVideosSortComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Sort by Date", None))
        self.sortTargetVideosDirectionButton.setText("")
#if QT_CONFIG(tooltip)
        self.targetVideosFilterMenuButton.setToolTip(QCoreApplication.translate("MainWindow", u"Target media filters", None))
#endif // QT_CONFIG(tooltip)
        self.targetVideosFilterMenuButton.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"File Type", None))
        self.targetVideosFilterImagesCheckBox.setText(QCoreApplication.translate("MainWindow", u"Images", None))
        self.targetVideosFilterVideosCheckBox.setText(QCoreApplication.translate("MainWindow", u"Videos", None))
        self.targetVideosFilterWebcamsCheckBox.setText(QCoreApplication.translate("MainWindow", u"Webcams", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Height", None))
        self.targetVideosHeightSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u"px", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Width", None))
        self.targetVideosWidthSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u"px", None))
        self.targetVideosListProgressBar.setFormat(QCoreApplication.translate("MainWindow", u"Loading Target Media %v/%m", None))
        self.input_Faces_DockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Input Faces", None))
        self.inputFacesPathLineEdit.setText("")
        self.inputFacesPathLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Select Face Images Path", None))
#if QT_CONFIG(tooltip)
        self.buttonInputFacesPath.setToolTip(QCoreApplication.translate("MainWindow", u"Choose Input Faces Folder", None))
#endif // QT_CONFIG(tooltip)
        self.buttonInputFacesPath.setText("")
        self.inputFacesSearchBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search Faces", None))
        self.jobManagerDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Job Manager", None))
        self.addJobButton.setText(QCoreApplication.translate("MainWindow", u"Save Job", None))
        self.loadJobButton.setText(QCoreApplication.translate("MainWindow", u"Load Job", None))
        self.deleteJobButton.setText(QCoreApplication.translate("MainWindow", u"Delete Job", None))
        self.refreshJobListButton.setText(QCoreApplication.translate("MainWindow", u"Refresh Job List", None))
        self.buttonProcessAll.setText(QCoreApplication.translate("MainWindow", u"Process All", None))
        self.buttonProcessSelected.setText(QCoreApplication.translate("MainWindow", u"Process Selected", None))
        self.controlOptionsDockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.face_swap_tab), QCoreApplication.translate("MainWindow", u"Face Swap", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.face_editor_tab), QCoreApplication.translate("MainWindow", u"Face Editor", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.common_tab), QCoreApplication.translate("MainWindow", u"Restorers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.denoiser_tab), QCoreApplication.translate("MainWindow", u"Denoiser", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Output Directory", None))
        self.outputFolderButton.setText(QCoreApplication.translate("MainWindow", u"Browse Folder", None))
        self.outputOpenButton.setText(QCoreApplication.translate("MainWindow", u"Open Folder", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings_tab), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.labelp.setText(QCoreApplication.translate("MainWindow", u"Presets", None))
        self.applyPresetButton.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.savePresetButton.setText(QCoreApplication.translate("MainWindow", u"Save Current as Preset", None))
        self.controlPresetButton.setText(QCoreApplication.translate("MainWindow", u"Apply Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preset_tab), QCoreApplication.translate("MainWindow", u"Presets", None))
        self.clearMemoryButton.setText(QCoreApplication.translate("MainWindow", u"Clear VRAM", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    # retranslateUi
